name: commit-linter
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0
        with:
          fetch-depth: 0
      - name: Install CommitLint and Dependencies
        run: npm install @commitlint/config-conventional @commitlint/cli
      - name: Lint Commits
        run: |
          first_commit=${{ github.event.pull_request.base.sha }}
          last_commit=${{ github.event.pull_request.head.sha }}
          npx commitlint --from $first_commit --to $last_commit -V
